package uit.elib.entities;
// Generated Nov 22, 2011 4:45:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Lecture generated by hbm2java
 */
public class Lecture  implements java.io.Serializable {


     private int lectureId;
     private Subject subject;
     private Integer order;
     private String summary;
     private String summaryVn;
     private String lectureName;
     private String lectureNameVn;
     private Set resources = new HashSet(0);

    public Lecture() {
    }

	
    public Lecture(int lectureId) {
        this.lectureId = lectureId;
    }
    public Lecture(int lectureId, Subject subject, Integer order, String summary, String summaryVn, String lectureName, String lectureNameVn, Set resources) {
       this.lectureId = lectureId;
       this.subject = subject;
       this.order = order;
       this.summary = summary;
       this.summaryVn = summaryVn;
       this.lectureName = lectureName;
       this.lectureNameVn = lectureNameVn;
       this.resources = resources;
    }
   
    public int getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(int lectureId) {
        this.lectureId = lectureId;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getSummaryVn() {
        return this.summaryVn;
    }
    
    public void setSummaryVn(String summaryVn) {
        this.summaryVn = summaryVn;
    }
    public String getLectureName() {
        return this.lectureName;
    }
    
    public void setLectureName(String lectureName) {
        this.lectureName = lectureName;
    }
    public String getLectureNameVn() {
        return this.lectureNameVn;
    }
    
    public void setLectureNameVn(String lectureNameVn) {
        this.lectureNameVn = lectureNameVn;
    }
    public Set getResources() {
        return this.resources;
    }
    
    public void setResources(Set resources) {
        this.resources = resources;
    }




}


