package uit.elib.entities;
// Generated Nov 25, 2011 12:35:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Resource generated by hbm2java
 */
public class Resource  implements java.io.Serializable {


     private Integer resourceId;
     private Resourcecategory resourcecategory;
     private Subject subject;
     private String resourceName;
     private Integer size;
     private String serverName;
     private String summary;
     private Date postDate;
     private Integer viewerNumber;
     private Integer downloadNumber;
     private String format;
     private String language;
     private Integer voteMark;
     private String resourceNameVn;
     private String summaryVn;
     private Integer oderChapter;
     private String author;

    public Resource() {
    }

    public Resource(Resourcecategory resourcecategory, Subject subject, String resourceName, Integer size, String serverName, String summary, Date postDate, Integer viewerNumber, Integer downloadNumber, String format, String language, Integer voteMark, String resourceNameVn, String summaryVn, Integer oderChapter, String author) {
       this.resourcecategory = resourcecategory;
       this.subject = subject;
       this.resourceName = resourceName;
       this.size = size;
       this.serverName = serverName;
       this.summary = summary;
       this.postDate = postDate;
       this.viewerNumber = viewerNumber;
       this.downloadNumber = downloadNumber;
       this.format = format;
       this.language = language;
       this.voteMark = voteMark;
       this.resourceNameVn = resourceNameVn;
       this.summaryVn = summaryVn;
       this.oderChapter = oderChapter;
       this.author = author;
    }
   
    public Integer getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
    public Resourcecategory getResourcecategory() {
        return this.resourcecategory;
    }
    
    public void setResourcecategory(Resourcecategory resourcecategory) {
        this.resourcecategory = resourcecategory;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }
    public String getServerName() {
        return this.serverName;
    }
    
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public Integer getViewerNumber() {
        return this.viewerNumber;
    }
    
    public void setViewerNumber(Integer viewerNumber) {
        this.viewerNumber = viewerNumber;
    }
    public Integer getDownloadNumber() {
        return this.downloadNumber;
    }
    
    public void setDownloadNumber(Integer downloadNumber) {
        this.downloadNumber = downloadNumber;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public Integer getVoteMark() {
        return this.voteMark;
    }
    
    public void setVoteMark(Integer voteMark) {
        this.voteMark = voteMark;
    }
    public String getResourceNameVn() {
        return this.resourceNameVn;
    }
    
    public void setResourceNameVn(String resourceNameVn) {
        this.resourceNameVn = resourceNameVn;
    }
    public String getSummaryVn() {
        return this.summaryVn;
    }
    
    public void setSummaryVn(String summaryVn) {
        this.summaryVn = summaryVn;
    }
    public Integer getOderChapter() {
        return this.oderChapter;
    }
    
    public void setOderChapter(Integer oderChapter) {
        this.oderChapter = oderChapter;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }




}


