package uit.elib.entities;
// Generated Nov 26, 2011 12:46:52 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private Integer subjectID;
     private SubjectCategory subjectcategory;
     private Faculty faculty;
     private String subjectNameVN;
     private String subjectNameEN;
     private String subjectIntroduceVN;
     private String subjectIntroduceEN;
     private Integer numberOfCredit;
     private String level;
     private Integer periodOfTheory;
     private Integer periodOfPractice;
     private String courseCode;
     private String teacher;
     private String prerequisiteSubjectVN;
     private String prerequisiteSubjectEN;
     private Integer midtermGrade;
     private Integer finalGrade;
     private String timeTeaching;
     private String projectRequirementVN;
     private String projectRequirementEN;
     private Set resources = new HashSet(0);

    public Subject() {
    }

    public Subject(SubjectCategory subjectcategory, Faculty faculty, String subjectNameEN, String subjectIntroduceEN, Integer numberOfCredit, String level, Integer periodOfTheory, Integer periodOfPractice, String courseCode, String teacher, String prerequisiteSubjectEN, String prerequisiteSubjectVN, Integer midtermGrade, Integer finalGrade, String subjectNameVN, String subjectIntroduceVN, String timeTeaching, String projectRequirementEN, String projectRequirementVN, Set resources) {
       this.subjectcategory = subjectcategory;
       this.faculty = faculty;
       this.subjectNameEN = subjectNameEN;
       this.subjectIntroduceEN = subjectIntroduceEN;
       this.numberOfCredit = numberOfCredit;
       this.level = level;
       this.periodOfTheory = periodOfTheory;
       this.periodOfPractice = periodOfPractice;
       this.courseCode = courseCode;
       this.teacher = teacher;
       this.prerequisiteSubjectEN = prerequisiteSubjectEN;
       this.prerequisiteSubjectVN = prerequisiteSubjectVN;
       this.midtermGrade = midtermGrade;
       this.finalGrade = finalGrade;
       this.subjectNameVN = subjectNameVN;
       this.subjectIntroduceVN = subjectIntroduceVN;
       this.timeTeaching = timeTeaching;
       this.projectRequirementEN = projectRequirementEN;
       this.projectRequirementVN = projectRequirementVN;
       this.resources = resources;
    }
   
    public Integer getSubjectID() {
        return this.subjectID;
    }
    
    public void setSubjectID(Integer subjectID) {
        this.subjectID = subjectID;
    }
    public SubjectCategory getSubjectcategory() {
        return this.subjectcategory;
    }
    
    public void setSubjectcategory(SubjectCategory subjectcategory) {
        this.subjectcategory = subjectcategory;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public String getSubjectNameEN() {
        return this.subjectNameEN;
    }
    
    public void setSubjectNameEN(String subjectNameEN) {
        this.subjectNameEN = subjectNameEN;
    }
    public String getSubjectIntroduceEN() {
        return this.subjectIntroduceEN;
    }
    
    public void setSubjectIntroduceEN(String subjectIntroduceEN) {
        this.subjectIntroduceEN = subjectIntroduceEN;
    }
    public Integer getNumberOfCredit() {
        return this.numberOfCredit;
    }
    
    public void setNumberOfCredit(Integer numInteger) {
        this.numberOfCredit = numberOfCredit;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public Integer getPeriodOfTheory() {
        return this.periodOfTheory;
    }
    
    public void setPeriodOfTheory(Integer periodOfTheory) {
        this.periodOfTheory = periodOfTheory;
    }
    public Integer getPeriodOfPractice() {
        return this.periodOfPractice;
    }
    
    public void setPeriodOfPractice(Integer periodOfPractice) {
        this.periodOfPractice = periodOfPractice;
    }
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
    public String getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }
    public String getPrerequisiteSubjectEN() {
        return this.prerequisiteSubjectEN;
    }
    
    public void setPrerequisiteSubjectEN(String prerequisiteSubjectEN) {
        this.prerequisiteSubjectEN = prerequisiteSubjectEN;
    }
    public String getPrerequisiteSubjectVN() {
        return this.prerequisiteSubjectVN;
    }
    
    public void setPrerequisiteSubjectVN(String prerequisiteSubjectVN) {
        this.prerequisiteSubjectVN = prerequisiteSubjectVN;
    }
    public Integer getMidtermGrade() {
        return this.midtermGrade;
    }
    
    public void setMidtermGrade(Integer midtermGrade) {
        this.midtermGrade = midtermGrade;
    }
    public Integer getFinalGrade() {
        return this.finalGrade;
    }
    
    public void setFinalGrade(Integer finalGrade) {
        this.finalGrade = finalGrade;
    }
    public String getSubjectNameVN() {
        return this.subjectNameVN;
    }
    
    public void setSubjectNameVN(String subjectNameVN) {
        this.subjectNameVN = subjectNameVN;
    }
    public String getSubjectIntroduceVN() {
        return this.subjectIntroduceVN;
    }
    
    public void setSubjectIntroduceVN(String subjectIntroduceVN) {
        this.subjectIntroduceVN = subjectIntroduceVN;
    }
    public String getTimeTeaching() {
        return this.timeTeaching;
    }
    
    public void setTimeTeaching(String timeTeaching) {
        this.timeTeaching = timeTeaching;
    }
    public String getProjectRequirementEN() {
        return this.projectRequirementEN;
    }
    
    public void setProjectRequirementEN(String projectRequirementEN) {
        this.projectRequirementEN = projectRequirementEN;
    }
    public String getProjectRequirementVN() {
        return this.projectRequirementVN;
    }
    
    public void setProjectRequirementVN(String projectRequirementVN) {
        this.projectRequirementVN = projectRequirementVN;
    }
    public Set getResources() {
        return this.resources;
    }
    
    public void setResources(Set resources) {
        this.resources = resources;
    }




}


