package uit.elib.dto;
// Generated Feb 17, 2012 11:57:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Groupdetail generated by hbm2java
 */
public class Groupdetail  implements java.io.Serializable {


     private Integer groupDetailId;
     private Group group;
     private Resourcecategory resourcecategory;
     private Integer value;

    public Groupdetail() {
    }

    public Groupdetail(Group group, Resourcecategory resourcecategory, Integer value) {
       this.group = group;
       this.resourcecategory = resourcecategory;
       this.value = value;
    }
   
    public Integer getGroupDetailId() {
        return this.groupDetailId;
    }
    
    public void setGroupDetailId(Integer groupDetailId) {
        this.groupDetailId = groupDetailId;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Resourcecategory getResourcecategory() {
        return this.resourcecategory;
    }
    
    public void setResourcecategory(Resourcecategory resourcecategory) {
        this.resourcecategory = resourcecategory;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }




}


