package uit.elib.dto;
// Generated Feb 4, 2012 2:04:56 AM by Hibernate Tools 3.2.1.GA



/**
 * Ip generated by hbm2java
 */
public class Ip  implements java.io.Serializable {


     private Integer ipid;
     private String ipvalue;
     private Byte ipstatus;

    public Ip() {
    }

    public Ip(String ipvalue, Byte ipstatus) {
       this.ipvalue = ipvalue;
       this.ipstatus = ipstatus;
    }
   
    public Integer getIpid() {
        return this.ipid;
    }
    
    public void setIpid(Integer ipid) {
        this.ipid = ipid;
    }
    public String getIpvalue() {
        return this.ipvalue;
    }
    
    public void setIpvalue(String ipvalue) {
        this.ipvalue = ipvalue;
    }
    public Byte getIpstatus() {
        return this.ipstatus;
    }
    
    public void setIpstatus(Byte ipstatus) {
        this.ipstatus = ipstatus;
    }




}


