package uit.elib.entities;
// Generated Dec 5, 2011 9:18:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private int facultyId;
     private String facultyNameEn;
     private String facultyNameVn;
     private Set subjects = new HashSet(0);

    public Faculty() {
    }

	
    public Faculty(int facultyId) {
        this.facultyId = facultyId;
    }
    public Faculty(int facultyId, String facultyNameEn, String facultyNameVn, Set subjects) {
       this.facultyId = facultyId;
       this.facultyNameEn = facultyNameEn;
       this.facultyNameVn = facultyNameVn;
       this.subjects = subjects;
    }
   
    public int getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(int facultyId) {
        this.facultyId = facultyId;
    }
    public String getFacultyNameEn() {
        return this.facultyNameEn;
    }
    
    public void setFacultyNameEn(String facultyNameEn) {
        this.facultyNameEn = facultyNameEn;
    }
    public String getFacultyNameVn() {
        return this.facultyNameVn;
    }
    
    public void setFacultyNameVn(String facultyNameVn) {
        this.facultyNameVn = facultyNameVn;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }




}


