package uit.elib.entities;
// Generated Nov 21, 2011 11:35:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Resource generated by hbm2java
 */
public class Resource  implements java.io.Serializable {


     private int resourceId;
     private Resourcecategory resourcecategory;
     private Subject subject;
     private String resourceName;
     private Integer size;
     private String serverName;
     private String summary;
     private Date postDate;
     private Integer viewerNumber;
     private Integer downloadNumber;
     private String format;
     private String language;
     private Integer voteMark;
     private String resourceNameVn;
     private String summaryVn;
     private Set lectures = new HashSet(0);

    public Resource() {
    }

	
    public Resource(int resourceId) {
        this.resourceId = resourceId;
    }
    public Resource(int resourceId, Resourcecategory resourcecategory, Subject subject, String resourceName, Integer size, String serverName, String summary, Date postDate, Integer viewerNumber, Integer downloadNumber, String format, String language, Integer voteMark, String resourceNameVn, String summaryVn, Set lectures) {
       this.resourceId = resourceId;
       this.resourcecategory = resourcecategory;
       this.subject = subject;
       this.resourceName = resourceName;
       this.size = size;
       this.serverName = serverName;
       this.summary = summary;
       this.postDate = postDate;
       this.viewerNumber = viewerNumber;
       this.downloadNumber = downloadNumber;
       this.format = format;
       this.language = language;
       this.voteMark = voteMark;
       this.resourceNameVn = resourceNameVn;
       this.summaryVn = summaryVn;
       this.lectures = lectures;
    }
   
    public int getResourceId() {
        return this.resourceId;
    }
    
    public void setResourceId(int resourceId) {
        this.resourceId = resourceId;
    }
    public Resourcecategory getResourcecategory() {
        return this.resourcecategory;
    }
    
    public void setResourcecategory(Resourcecategory resourcecategory) {
        this.resourcecategory = resourcecategory;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }
    public String getServerName() {
        return this.serverName;
    }
    
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public Integer getViewerNumber() {
        return this.viewerNumber;
    }
    
    public void setViewerNumber(Integer viewerNumber) {
        this.viewerNumber = viewerNumber;
    }
    public Integer getDownloadNumber() {
        return this.downloadNumber;
    }
    
    public void setDownloadNumber(Integer downloadNumber) {
        this.downloadNumber = downloadNumber;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public Integer getVoteMark() {
        return this.voteMark;
    }
    
    public void setVoteMark(Integer voteMark) {
        this.voteMark = voteMark;
    }
    public String getResourceNameVn() {
        return this.resourceNameVn;
    }
    
    public void setResourceNameVn(String resourceNameVn) {
        this.resourceNameVn = resourceNameVn;
    }
    public String getSummaryVn() {
        return this.summaryVn;
    }
    
    public void setSummaryVn(String summaryVn) {
        this.summaryVn = summaryVn;
    }
    public Set getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set lectures) {
        this.lectures = lectures;
    }




}


