package uit.elib.entities;
// Generated Nov 26, 2011 12:46:52 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subjectcategory generated by hbm2java
 */
public class SubjectCategory  implements java.io.Serializable {


     private int subjectCategoryID;
     private String subjectCategoryNameEN;
     private String subjectCategoryNameVN;
     private Set subjects = new HashSet(0);

    public SubjectCategory() {
    }

	
    public SubjectCategory(int subjectCategoryID) {
        this.subjectCategoryID = subjectCategoryID;
    }
    public SubjectCategory(int subjectCategoryID, String subjectCategoryNameEN, String subjectCategoryNameVN, Set subjects) {
       this.subjectCategoryID = subjectCategoryID;
       this.subjectCategoryNameEN = subjectCategoryNameEN;
       this.subjectCategoryNameVN = subjectCategoryNameVN;
       this.subjects = subjects;
    }
   
    public int getSubjectCategoryID() {
        return this.subjectCategoryID;
    }
    
    public void setSubjectCategoryID(int subjectCategoryID) {
        this.subjectCategoryID = subjectCategoryID;
    }
    public String getSubjectCategoryNameEN() {
        return this.subjectCategoryNameEN;
    }
    
    public void setSubjectCategoryNameEN(String subjectCategoryNameEN) {
        this.subjectCategoryNameEN = subjectCategoryNameEN;
    }
    public String getSubjectCategoryNameVN() {
        return this.subjectCategoryNameVN;
    }
    
    public void setSubjectCategoryNameVN(String subjectCategoryNameVN) {
        this.subjectCategoryNameVN = subjectCategoryNameVN;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }




}


